### ISSUE TITLE
Restrict parallelism of builds.

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/automation-for-humans#3]
Currently we have as many processes as many as number of tests.

[Code here](https://github.com/intuit/automation-for-humans/blob/91d13f34c493905c7c8b200661d4a8ca9513f177/src/automate.py#L212) does this.

Change it to a config driven code that takes in a parameter on level of parallelism.

**Comment by kmmanoj** [comment]
I can use configparser to solve this issue.

**Comment by MadaraUchiha-314** [comment]
@kmmanoj The better place to specify the parallelism is at the suite level. You would have to decide on the parallelism before this line : https://github.com/intuit/automation-for-humans/blob/master/src/automate.py#L209

**Comment by t-gok** [comment]
I can solve this, let me know if the issue is currently not being worked on
