### ISSUE TITLE
Fix build timeout issue in appveyor

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/automation-for-humans#31]
Builds are timing out even after successful completion and this is causing wrong badge status in the README. This issue is only related to windows. Verified that it does not happen locally.

Potentially due to the behavior differences between how the process exits in windows and unix environments.

**Comment by v1shwa** [comment]
Hi, @MadaraUchiha-314  I can work on this. Can you assign this to me?

**Comment by MadaraUchiha-314** [comment]
@v1shwa I suggest you fork the repository and then work on it. I saw that you have cloned my repo and created a new repo out of it which might not be the open-source way of doing things.

**Comment by v1shwa** [comment]
@MadaraUchiha-314 Sure, I will be raising the PR from the fork which I have created here https://github.com/v1shwa/automation-for-humans !
