### ISSUE TITLE
Custom file extension and syntax highlighting for the DSL

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/automation-for-humans#38]
- Using the grammar for DSL can we easily syntax highlight it ?
- Which editors are we targeting ?
    - Atom
    - VS Code

**Comment by Einsteino** [comment]
This looks interesting! I'll have a look at this over the weekend. Looks like basic syntax highlights should be possible, will try making an Atom extension.

**Comment by MadaraUchiha-314** [comment]
@Einsteino Want to know why you specifically chose Atom ? Why not VSCode ? We have other roadmap items that target using VSCode as the debugger. Look at #39

**Comment by Einsteino** [comment]
As a starting point; I've dabbled with Atom extensions before. I think it should be extended easily to VSCode as well.

**Comment by Einsteino** [comment]
Can we chat about this sometime? 
The grammar seems pretty simple - there's no nesting/loops, etc; so defining highlights for this grammar should be straightforward. 

Where can I push an extension's code?

**Comment by MadaraUchiha-314** [comment]
You can push the extensions code here : https://github.com/orgs/automation-for-humans
