### ISSUE TITLE
Generate pretty reports from test runs

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/automation-for-humans#40]
What are the standard report formats ? Are they applicable for UI tests ? Do we get the test reports on PR's ?

Some formats :
- Cobertua XML

**Comment by trafaliya** [comment]
Will create standard NUnit XML reports( based on https://github.com/nunit/docs/wiki/Test-Result-XML-Format). Should be applicable for the framework from the looks of it.

**Comment by MadaraUchiha-314** [comment]
@trafaliya Would like to look at what are the industry standards for such reports ? Having a comparison between multiple formats would give us better clarity.

**Comment by trafaliya** [comment]
JUnit - https://stackoverflow.com/questions/4922867/what-is-the-junit-xml-format-specification-that-hudson-supports
XUnit - http://reflex.gforge.inria.fr/xunit.html#xunitReport

These are some more standard XML reports that are used, generally for unit tests. All are pretty similar, we can choose any one of these.
